### ISSUE TITLE
Councils not being able to create community services

### ISSUE THREAD

**Issue by daliusl** [rogerthat-platform/rogerthat-backend#114]
change request: https://docs.greenitglobe.com/gig/proj_actives/issues/2

**Comment by RubenMattan** [comment]
By default they are only allowed to create associations when you want to change that just check the organization types you want them to be able to create/access.

<img width="1164" alt="screen shot 2017-03-14 at 15 06 50" src="https://cloud.githubusercontent.com/assets/1122760/23904357/e1ae3284-08c7-11e7-9b12-623b2d1127bc.png">
