### ISSUE TITLE
Custom icons for apps and services

### ISSUE THREAD

**Issue by daliusl** [rogerthat-platform/rogerthat-backend#118]
change request: https://docs.greenitglobe.com/gig/proj_actives/issues/12

**Comment by abdulgig** [comment]
Just following up here, please let us know the ETA so that the customer can be updated accordingly.

Thanks,

**Comment by FastGeert** [comment]
Won't fix

**Comment by FastGeert** [comment]
Maybe interesting for the future. Will put it in backlog.

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#48
