### ISSUE TITLE
Custom welcome message is not used?

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#139]
There is a custom welcome message set for the Elisabeth Begijnhof app using app translations. However, the default welcome message is sent.

![screen shot 2017-04-28 at 15 08 55](https://cloud.githubusercontent.com/assets/17762105/25530395/65f256c0-2c26-11e7-9b8f-e446b85ea72c.png)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#93
