### ISSUE TITLE
Show response when services don't return JSON data

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#14]
Now request and response are empty in the service logs. This should not be the case.

![screen shot 2016-10-12 at 12 24 25](https://cloud.githubusercontent.com/assets/17762105/19306654/f59c2608-9076-11e6-9053-21eab491c51a.png)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#54
