### ISSUE TITLE
/mobi/rest/system/log_error sends an empty dict instead of a unicode on Edge

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#188]
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063"

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#92
