### ISSUE TITLE
Payments - datastore cleanup

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#189]
Every day or so, cleanup these objects:
- PaymentOauthLoginState
- PaymentPendingReceive

**Comment by RubenMattan** [comment]
We should indeed invalidate PaymentPendingReceive but i would not delete anything

**Comment by lucasvanhalst** [comment]
Guess we aren't cleaning it up then

**Comment by RubenMattan** [comment]
Well i want to keep al the data (for now at least)
