### ISSUE TITLE
Make it possible to redirect to a custom sign in page based on URL

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#206]
When the "/" handler is being requested by using "dashboard.onzestadapp.be", then redirect to "/customers/signin".

You need to check the X-Forwarded-For request header for this.

Make this configurable.

**Comment by abom** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/130/commits/2faa414805ea9afcc097f39c97ae2dcac472a13b
