### ISSUE TITLE
Embedded app translations

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#220]
~- [ ] Create getEmbeddedAppTranslations call: This fetches translations for each embedded_cordova_app that is activated in the app. These translations are then stored in the app its database.~ we will only use update since we will be using the heartbeat method to update the translations
- [x] Create updateEmbeddedAppTranslations call (this would be called manually by us after we update the translations on the servers)
- [x] Create getTranslations method in rogerthat cordova plugin (this will _only_ fetch translations for the currently opened app, e.g. rogerthat-payment

Translations to store for rogerthat-payments:
- asset types
- payment providers (use '{payment_provider_id}_description' as translation key)

The above can also be used to update existing translations inside an embedded cordova app without having to update the app in Google Play / Appstore

Only fetch these translations the first time getTranslations is called in the app.

**Comment by RubenMattan** [comment]
Instead of saving embedded_cordova_apps into the app model let the phone tell what cordova_apps he has. When the phone send a heartbeat also request translations for all his cordova_apps.

**Comment by RubenMattan** [comment]
These translations should be stored like this:
app_name | json_translations_for_my_language
