### ISSUE TITLE
Limit request data  when logging service activity

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#228]
log_service_activity for brandings tries to log the entire branding that had been uploaded, prevent this by checking the length of the request data, if it is larger than 800KB, json parse it and replace values of the properties that are longer than 100K with some dummy data

https://github.com/rogerthat-platform/rogerthat-backend/blob/07d6f0d58b64d1a70d7aff3b9125775a2f1ccaeb/src/rogerthat/rpc/service.py#L471

**Comment by RubenMattan** [comment]
Can you also log an error message for other methods that are bigger then 500kb

**Comment by lucasvanhalst** [comment]
Done
