### ISSUE TITLE
Add sorting boolean to serviceTO.actionMenu

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#280]
- Add boolean `sortActionMenu` to `ServiceProfile`.
- Show it in the service panels in the Service Menu page, or the Profile page. Depends on what's the easiest or most logical.
- When creating the ActionMenuTO and `sortActionMenu` is True, left-top-align all menu items, such that there are no "gaps" anymore in the menu.

**Comment by RubenMattan** [comment]
We are going to implement a gravity boolean on every menu item (disabled by default).
The clients will sort the menu items

**Comment by bart-at-mobicage** [comment]
Use the first row as well. so if the first menu item has gravity, and there's no call and/or recommend, then it's shown on the first row.
