### ISSUE TITLE
Sometimes the photo_upload result link doesn't work

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#288]
> Verzonden: woensdag 13 september 2017 13:59
> ...
> Message flow: Meldingskaart Website
> Tag: meldingskaart
> App: Neerpelt
> Gebruiker: ***@gmail.com (***@gmail.com)
> 
> ...
> 
>
> 6: Neem een foto van je melding of gebruik een reeds genomen foto vanuit je fotogalerij op je telefoon.
> Antwoord: https://rogerth.at/unauthenticated/mobi/service/photo/download/eyJwYXJlbnRfbWVzc2FnZV9rZXkiOiJfanNfYjIxMGJlZDAtNWU5NC05YjJmLWIyNGYtOGNhYzE5ZTU4ZmNjIiwibWVzc2FnZV9rZXkiOiJfanNfMzhhZjhkZmYtNmM5OS00MjhlLTEyMGMtYTUxMDdkNjA3MTYzIn0=
> Knop: Verder

Also, we should urlencode this url, because the `=` sign isn't included in the link when viewing in the OSX Mail app.

<img width="674" alt="screen shot 2017-09-15 at 14 55 19" src="https://user-images.githubusercontent.com/17762105/30483112-eb17cff2-9a25-11e7-988e-84ad50b2581c.png">

**Comment by RubenMattan** [comment]
Customer will contact us when they have the issue again
