### ISSUE TITLE
Corrupted ServiceIdentityStatistics

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#310]
Due to failures and retries in log_analysis?

![2017-10-09 15 20 43](https://user-images.githubusercontent.com/17762105/31340106-6f18d5ac-ad05-11e7-81b2-bec1a9336784.jpg)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#68
