### ISSUE TITLE
Cleanup unused translations

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#312]
`test_i18n.py` reported that there are `23 keys translated but not found in code`. Double check if they are really unused. Also remove them from Mobitrans to make sure they don't re-appear when exporting.
- `%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.`
- `%(name)s declined your request to track his/her location.`
- `%(name)s does not have a device which supports location tracking.`
- `%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.`
- `Associations`
- `Care`
- `Community Services`
- `Invalid download_url (%(url)s). It must be reachable over http or https.`
- `Merchants`
- `Please try again later.`
- `Service %(name)s wants to connect with you via %(app_name)s.`
- `Services`
- `There is no e-mail address configured in your facebook account. Please use the e-mail based login.`
- `This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.`
- `User %(name)s has requested to share your location.`
- `User %(name)s wants to get in touch with you via %(app_name)s.`
- `We could not determine the location of %(name)s.`
- `You are already connected with %(name)s.`
- `_welcome_message`
- `association`
- `community_service`
- `merchant`
- `service`

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#85
