### ISSUE TITLE
User registered at 15:00 and was still fetching news index at 18:00

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#314]
Happened in Sint-Truiden app
user: 213d41c81bd7de7c94b542136aae8c1f

![screen shot 2017-10-11 at 18 18 16](https://user-images.githubusercontent.com/17762105/31452959-b1c6fb3e-aeb0-11e7-8e02-bf3388cb964f.png)

![screen shot 2017-10-11 at 18 18 29](https://user-images.githubusercontent.com/17762105/31452973-b9d6cd40-aeb0-11e7-9d7d-e4940479e4a2.png)

![screen shot 2017-10-11 at 18 18 40](https://user-images.githubusercontent.com/17762105/31452981-bfb87c5e-aeb0-11e7-8fef-3d66b5661337.png)

![screen shot 2017-10-11 at 18 18 52](https://user-images.githubusercontent.com/17762105/31452987-c25a8060-aeb0-11e7-94d7-57f8be5c7703.png)

![screen shot 2017-10-11 at 18 19 05](https://user-images.githubusercontent.com/17762105/31452992-c563a8fe-aeb0-11e7-9de3-71b2a67a5b18.png)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#84
