### ISSUE TITLE
Weird QR-based requests on rogerth.at

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#316]
Looks like the requests are coming from Facebook. So maybe the recommend feature in ios/android does something wrong?

/M/be-anzegem://q/s/h9cvIHLacLLZFsp8VhMqwhztj_ZJ6m0wk6m6ON6v5n8-/1
/M/be-anzegem://q/s/YB9mzrxis7pprL.w9dV8BRSeWw5cwN8zN3.LmGikwkY-/1

<img width="1131" alt="screen shot 2017-10-20 at 10 48 11" src="https://user-images.githubusercontent.com/17762105/31812717-3af29e70-b584-11e7-929b-9bb75854a18e.png">

**Comment by RubenMattan** [comment]
Tested android and iOS, both worked fine (Latest version)

**Comment by bart-at-mobicage** [comment]
I guess it's related to https://github.com/rogerthat-platform/rogerthat-backend/blob/master/src/rogerthat/pages/service_interact.py#L135 and https://github.com/rogerthat-platform/rogerthat-backend/blob/master/src/rogerthat/pages/service_interact_mobile.html#L29

**Comment by RubenMattan** [comment]
No that would mean they viewed the url correctly via a desktop, and the main app_id of that service is rogerthat.
We have incorrect urls from anzegem, halen, veurne, herk-de-stad, staden in the last 2 days

**Comment by bart-at-mobicage** [comment]
Another one, with Whatsapp??

![screen shot 2017-11-16 at 09 43 12](https://user-images.githubusercontent.com/17762105/32881781-99eeba60-cab2-11e7-87da-0110b27a5b08.png)

**Comment by RubenMattan** [comment]
The one from whatsapp is not a valid url

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#67
