### ISSUE TITLE
TransactionFailedError: too much contention on these datastore entities (Branding)

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#321]
We would better migrate all Brandings to the entity group of the service. And create a cached `get_branding_by_hash` method that can be used by the branding download handler. The method can filter the branding by hash. Within transactions we know the service user, so then we can still get them by key.

```
TransactionFailedError: too much contention on these datastore entities. please try again. entity group key: app: "e~rogerthat-server"
path <
  Element {
    type: "Branding"
    name: "EA956F30E8559D79BB0972D930F1AE544E35318750154416263A90F5E4B6E7BF"
  }
>
```

**Comment by lucasvanhalst** [comment]
In the future I would make the clients add the service email in the url when fetching a branding so that this cached method is not needed anymore for updated clients

e.g. /branding/service@rogerth.at/EA956F30E8559D79BB0972D930F1AE544E35318750154416263A90F5E4B6E7BF

**Comment by RubenMattan** [comment]
Its just the other way around.
https://cloud.google.com/appengine/articles/scaling/contention

**Comment by RubenMattan** [comment]
> Do not use a forward slash (/) in kind names or custom key names. Forward slashes in these names could interfere with future functionality.

https://cloud.google.com/datastore/docs/best-practices#designing_for_scale
