### ISSUE TITLE
Fetch user information after oauth registration

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#325]
get the oauth identity after registration https://github.com/rogerthat-platform/rogerthat-backend/blob/31645b770ee70c023a542e52915f3780e69db5f5/src/rogerthat/pages/register_mobile.py#L979

and use the provided information to pre-fill the userprofile with email (<username>@<oauth_domain>), qualified identifier (real email address to be shown in UI), and name

Also extend RegistrationResultTO with this same info

**Comment by RubenMattan** [comment]
Only implement RegistrationResultTO with extra info
