### ISSUE TITLE
Add 'required' property to most flow steps

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#354]
Add `validation` property to FormTO with currently only one property `required`

Some questions:

- What should the error message be? 
- What do we do with existing 'required' properties (like on GPS widget)

Inspiration for possible future build-in validations: https://angular.io/api/forms/Validators

**Comment by bart-at-mobicage** [comment]
We're gonna implement it as follow:
- [ ] In the javascript validation editor in the message flow designer, add a button to add a code snippet to check if the input isn't empty
  - Ask for the error message (default to "This is a required field")
