### ISSUE TITLE
AppData values are not deleted on client when deleted on server

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#364]
Scenario:
- `put_service_data({"a": 1, "b": 2})`
  - app_data = `{"a": 1, "b": 2}`
  - request sent to client contains `{"a": 1, "b": 2}`
- `put_service_data({"b": None})`
  - app_data = `{"a": 1}`
  - request sent to client contains `{"a": 1}`

In the last step, the client receives `{"a": 1}` instead of `{"a": 1, "b": null}`. Null should be sent such that the clients can delete the key.

**Comment by abom** [comment]
This log shows that null values are sent

`system.put_service_data(json.dumps({"b": None}))
`
`[XX-OFFLOADv1] {"type":"api","response_data":null,"user":"b9c3c33439db8e2a107949aaf99099b7","timestamp":1515071975,"success":true,"function":"system.put_service_data","request_data":{"data":"{\"b\":null}"}}
`

**Comment by RubenMattan** [comment]
We are going to keep a version and all changed keys in the KeyValue model. That way we can only send the changes to all the mobiles.

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#66
