### ISSUE TITLE
Ask to continue registration before logging out another device

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#368]
When installing the app with the same user on a 2nd device
- [ ] show the user that he will be logged out on his 1st device (Show model name. Eg. iPhone X) and ask him to confirm to continue.
- [ ] when continued, show on his 1st device that it has been logged out because of login on another device (Show model name. Eg. Samsung Galaxy 8)

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/378
