### ISSUE TITLE
Link Payment Providers to apps

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#416]
Right now, all payment providers are visible in all apps that have the `rogerthat-payment` embedded app. We must be able to configure this. Eg. Payment Provider `Payconiq` should only be visible in all Belgian city apps. And Payment Provider `ThreeFold` should only be visible in the ThreeFold app.

I propose to add an array of regexes to the `PaymentProvider` model. If any regex matches, then that payment provider is visible in that app.

Feel free to propose a different solution if you think of one.

**Comment by abom** [comment]
The other way around is to just configure payment providers for every app, or even add all by default to every app, and enable excluding any of them later?

**Comment by bart-at-mobicage** [comment]
For now, the wallet won't be visible in the city app. And the existing TF wallet will be replaced with one that uses another backend.
