### ISSUE TITLE
Invalid registration signature

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#418]
Lots of registrations fail in the register_devices step. The request returns 500 without logging something. So I think the signature is incorrect. Search for register_devices in the server logs on any log level.

**Comment by RubenMattan** [comment]
Fixed by https://github.com/rogerthat-platform/rogerthat-android-client/commit/5c204313a4a350edddf29089f368565eed3a6b1c
