### ISSUE TITLE
Embedded apps in peer to peer messaging

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#448]
A message will have a new property `embedded_app` this property will have 3 properties named `id`, `context` and `locked_context`.

Embedded apps launched by peer to peer messages will be able to do the following:
- send a new message in the chat
- optionally update the current message (`locked_context` only)

We will need to add `update_message` to get the updated `locked_context` to the other members

A chat will have new 2 new `flags` namely `FLAG_ALLOW_CHAT_GAMES` and `FLAG_ALLOW_CHAT_PAYMENTS` 
This will result in 2 extra buttons when clicked this will load payment provider / games from the database.

Embedded apps will need to have a `rogerthat_thread_icon.png` and `rogerthat_config.json` in their branding so they can be displayed nicely in the message list

rogerthat_config.json will have the following properties:
- `name` string
- `description` string
- `types` string[]

Types can be one of the following TBD (`messaging_games`, `messaging_payments`, `widget_pay`, ...)

The icon and config should be validated when uploading an embedded app. Then the config should be added to the app model and TO

Example game chess (No server needed):
1st message context will contain context with sender_email and all positions of the pieces, when he moves a piece the from and to of that piece will be in locked_context. Then a new message with the new position of all pieces will be send.

**Comment by lucasvanhalst** [comment]
I think it would be better to add the icon / picture url to the message itself, this has the advantage of not having to download the embedded app before being able to properly show the message, plus the embedded app it's size will be smaller. Facebook for example does the same thing:

![screen shot 2018-04-05 at 15 01 01](https://user-images.githubusercontent.com/6652304/38367223-60334a54-38e2-11e8-97db-2a93163c2097.png)

If we ever decide to make a web client this would also be better as we wouldn't have to download it too

**Comment by RubenMattan** [comment]
Flags on a message are used to enabled or disable functionality in a thread. So we need 2 new flags to enable/disable games and/or payments in a thread.

**Comment by RubenMattan** [comment]
icon, name and description can indeed be added to the message in case we don't want to download all embedded apps by default. Then the image custom for every user / step ... 

Types however was intended so you didn't need to go to the server to see every game/payment app available.

**Comment by lucasvanhalst** [comment]
A message will have a new property `embedded_app` this property will have the following properties:

```typescript
interface MessageEmbeddedapp {
    id: number;
    context: any;  // data to be provided to the embedded app
    result?: any; // result from embedded app
    /* properties set via server */
    icon_url?: string;
    title?: string;
    description?: string;
}

```


Example
```
{
    id: 123,
    context: {
        to: 'jefke@rogerthat.net',
        amount: 4210,
        precision: 2,
        currency: 'EUR',
        test_mode: false,
    },
    result: null,  // Transaction id will be in here after payment is complete
    image_url: 'https://...',
    title: 'Payment',
    description: 'Pay 42.10 EUR to Jefke'
}
```

Embedded apps launched by peer to peer messages will be able to update the current message its embedded_app properties once (everything except `id` and `context`)
We will need to add an `updateMessage` client -> server call for this

A chat will have 2 new flags FLAG_ALLOW_CHAT_GAMES and FLAG_ALLOW_CHAT_PAYMENTS

This means that old chats will never have these options. Is this ok? If I had a chat with someone and keep using the same chat, I'll never be able to send a payment.

- Add property `types` to EmbeddedApp.

This is to  indicate where this embedded app can be used (e.g. pay_widget, messaging_games, messaging_payment). Validate flows that they have the messaging_payment type

This will result in 2 extra buttons when clicked this will load embedded apps from server (filtered by `type`)

**Comment by lucasvanhalst** [comment]
Also todo:

- [ ] Add `title` and `description` property to embedded apps, to be shown to the user when choosing an embedded app for payment (or for other things later on)
- [ ] Update CC with updated EmbeddedApp model
