### ISSUE TITLE
Deeplinking from a service menu item to another app

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#451]
- First create spec
  - model
  - service api
  - TOs
- After review, start implementation

**Comment by RubenMattan** [comment]
Was thinking of replacing `link` with `open`.
Open has an `action` and `params`. This way its the same as our javascript api

**Comment by RubenMattan** [comment]
I just used the link param for the clients, but for the service api it may be useful to have a separate field

**Comment by RubenMattan** [comment]
We are going to allow putting `open://json_dict` on a link item. So no changes needed for this
