### ISSUE TITLE
Service disappearing from service index

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#455]
Looks like a Google problem...

`re_index` removes and adds the service identity to the search index. When trying to get the search document, ±19 out of 20 attempts returned nothing. Then I tried to cleanup the index. Wait a minute and add the index. Then it worked. But after an hour, the search document disappeared automagically. When retrying, almost all attempts failed again.

Only happened with `service-ec26c2a7-808f-45a9-a379-05cce4e15d5f@rogerth.at` so far. I tried with other services and those attempts succeeded.

```
def investigate_find_service():
  from google.appengine.api import search
  from rogerthat.dal.profile import get_search_config
  from rogerthat.bizz.service import SERVICE_INDEX, re_index
  si_email = 'service-ec26c2a7-808f-45a9-a379-05cce4e15d5f@rogerth.at/+default+'
  si_user = users.User(si_email)
  docs = None

  docs = re_index(si_user)
  time.sleep(2)

  the_index = search.Index(name=SERVICE_INDEX)
  get_result = the_index.get(si_email)

  query = search.Query("BokesBar")
  search_result = the_index.search(query)

  return get_result, search_result
```

**Comment by bart-at-mobicage** [comment]
Strangely, it worked when the service name was updated from 'BokesBar' to 'De BokesBar'.

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#76
