### ISSUE TITLE
payments: api call for getting payment providers with currency conversion ratios

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#460]
Per payment provider we need to be able to define multiple currencies. Per provider, an object should be returned to the client. These will be used to show a list of options that can be used to pay when paying via the pay widget

properties:

- logo_url
- provider_id
- embedded_app
- methods:
  - currency
  - amount
  - precision

On the pay widget:
- add 'base payment method'
  - currency,  provider
use this method to calculate the amount of the other methods if the boolean 'calculate_amount' on the form settings is true (true by default)

On payment provider model, store the conversion ratio:

```
conversion_ratio =  {
   'base': 'EUR',
   'values': [{'currency': 'USD', 'amount': 1.21}, {'currency': 'TFT', 'amount': 10.0}]
}
```

**Comment by RubenMattan** [comment]
related feature: https://github.com/rogerthat-platform/rogerthat-backend/issues/450
