### ISSUE TITLE
Services mentioned 3 times in search list

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#462]
There were some issues with the search index for this service #455 . I re_indexed it a lot. Now it's appearing multiple times in the search. 

![img_eb0bb4e5ac65-1](https://user-images.githubusercontent.com/17762105/38878575-8cba373a-4261-11e8-9a86-585dfc28eb03.jpeg)

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#75
