### ISSUE TITLE
getNews fails because request to influx timed out

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#473]
do we send a synchronous request for every news item that is requested?
why are the `get_..._from_influx_db` methods cached only on request level? it's not that this method will be executed multiple times in the same request.

server logs: [logs.txt](https://github.com/rogerthat-platform/rogerthat-backend/files/1954301/logs.txt)

**Comment by lucasvanhalst** [comment]
No, we send 3 synchronous requests for every news item.
It can be refactored so only 1 request is needed for a bunch of news items.
