### ISSUE TITLE
Extend run_job with a finalize function

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#482]
Refactor run_job to use Pipelines such that we can add a finalize step.

**Comment by RubenMattan** [comment]
What was the reason we wanted to build this?

**Comment by bart-at-mobicage** [comment]
to not have to refactor update_friends.py into pipeline, because we need a cleanup step in #430

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/505
