### ISSUE TITLE
The Channel API feature has been deprecated and is going to be removed

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#49]
Deadline October 31, 2017 https://cloud.google.com/appengine/docs/deprecations/channel
Alternative is using Firebase.

**Comment by bart-at-mobicage** [comment]
You can find inspiration [here](https://github.com/rogerthat-platform/gae-plugin-framework/blob/52bc1de93bf2078c5be7b709e3b38c013f6dc721/framework/server/framework/bizz/channel.py#L33) and on the internet (lot's of occurrences when searching for "howto replace channel api with firebase"
