### ISSUE TITLE
Need a clear service api exception in case a required param is missing

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#490]
Now it's just a regular "500: please contact support"

<img width="1347" alt="screen shot 2018-05-17 at 14 16 10" src="https://user-images.githubusercontent.com/17762105/40176798-e1f8e11e-59dc-11e8-8036-8b500793c9a0.png">

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#73
