### ISSUE TITLE
We need a userDataUpdated capi call

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#5]
Now, when the userData is updated, the full key-value store is pushed to the android/ios clients.

We need a userDataUpdated capi call such that a smaller change-set is pushed to the clients. The clients should also store the userData in a new table instead of saving the json string in the friend table.

**Comment by RubenMattan** [comment]
duplicate https://github.com/rogerthat-platform/rogerthat-backend/issues/224
