### ISSUE TITLE
There is something wrong with our branding hashes

### ISSUE THREAD

**Issue by RubenMattan** [rogerthat-platform/rogerthat-backend#509]
Expected 3C3867E404C8EEF86BB1B123EAE9C4AB93155FC4E5D2D5B79BBF86680545F55B
Got FA2FA21CC94AE0566320744EA25F988876E86C5A72AAEC87A6A2E9BE08B96EED (alken app)

Expected 6BEF53F4D34D31F66102922D6DFE6DBCDB2B7A7B5871DD8FD8420CF5EE0DD329
Got F09DDEF90BBBFA44CB576119699DB11155A2CCBD176447913E91AC531924C736 (Herentals app)

Expected 9644ABDB77DFE0982B54B717B74634D3A8F101DA392E1FF42AE59DCDA3EA321C
Got 4012BFD142333B14C98D5EA52107409CAF739FD1B969021FAB6C1D7D782F85D2 (Neerpelt app)

Failed to download branding file null for service 'dashboard@rogerth.at' and start flow hash: 5c1aac97b94ab3a6bd24ed7db51a6848
Failed to download branding file null for service 'dashboard@rogerth.at' and start flow hash: c1bb5ae2c3b4f038b985c2cbd094e973
Failed to download branding file null for service 'dashboard@rogerth.at' and start flow hash: e62dba923b73a67cf2db7e6084d70df5
Failed to download branding file 11570A997A2EBB4958482213A108BE11F48A640E62D8EC2C27535984B9CDEABD for service 'dashboard@rogerth.at' and start flow hash: 74299bd83ab38f4280b74b060e301643

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#62
