### ISSUE TITLE
Error in version of 'terms and conditions' page

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#550]
Is there something wrong with selecting an old version?

<img width="604" alt="screen shot 2018-07-09 at 08 36 02" src="https://user-images.githubusercontent.com/17762105/42434333-1b1cc61e-8353-11e8-92d0-ac33c1b2ad66.png">

**Comment by lucasvanhalst** [comment]
Issue migrated to our-city-app/mobicage-backend#69
