### ISSUE TITLE
Birthday messages should be sent without flag SHARED_MEMBERS

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#63]
Now the recipient sees every other recipient, which is not ideal.

![bug](https://cloud.githubusercontent.com/assets/17762105/22030852/418698a0-dcdf-11e6-86ad-75b43e92dabd.png)

**Comment by abom** [comment]
It's already sent [without SHARED_MEMBERS flag](https://github.com/rogerthat-platform/rogerthat-backend/blob/master/src/rogerthat/cron/birthday.py#L70).
