### ISSUE TITLE
Automated documentation

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/rogerthat-backend#84]
Generate documentation of API calls and the related objects automatically.

Specs TBD, but we could use http://www.sphinx-doc.org/en/stable/ for this I think to create documentation pages from existing docstrings

**Comment by abom** [comment]
Good, i think we should also choose a unified doc style that's supported by the doc generator.

**Comment by lucasvanhalst** [comment]
I'd opt for the google-style documentation but we'll have to discuss it http://www.sphinx-doc.org/en/1.5.2/ext/example_google.html
