### ISSUE TITLE
News feed filtered by role

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-backend#93]
- Extend the `target_audience` parameter of the `news.publish` call with an optional `role_ids` field.
- In `send_realtime_updates`, make sure that people which are not connected to the role don't receive a push notification / newsserver update / newNewsItem backlog call.
- In `com.mobicage.api.news.getNews`, skip the news items with roles the user is not assigned to.
  - If you had to skip all news items, then don't return an empty result. Get the next batch of news items
  - Eg. `get_all_news` fetches 100 items. They all have a role you're not assigned to. Then execute `get_all_news` again with the new cursor (unless `get_all_news` didn't return any result)

**Comment by abom** [comment]
In order to filter the news sent to app users, i think we need to send the users who shouldn't receive an update to the news server per a news item.

Also, matching the roles should affect the sort priority? (for match_target_audience).

**Comment by RubenMattan** [comment]
Providing the app users is not really scalable.
I would let the news server do an http request to the server to request the users that are in that role (max 1000 results with cursor)

**Comment by RubenMattan** [comment]
This will not affect sort_priority because the item will not be shown

**Comment by RubenMattan** [comment]
I had a talk with Geert
We are not going to send these news items to the news bot anymore

**Comment by abom** [comment]
@bart-at-mobicage How we will implement this in [oca-backend](https://github.com/our-city-app/oca-backend)?

**Comment by bart-at-mobicage** [comment]
it's not related to oca-backend. It's for a partner who's programming on top of Rogerthat. They want to show different news items depending on the function you have in the company.
